export const authAction = {
  LOGIN_BEGIN: "LOGIN_BEGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_BEGIN",
  LOGOUT_BEGIN: "LOGOUT_BEGIN",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",
};
export const userAction = {
  GET_USER_BEGIN: "GET_USER_BEGIN",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_BEGIN",
  GET_LISTUSER_BEGIN: "GET_LISTUSER_BEGIN",
  GET_LISTUSER_SUCCESS: "GET_LISTUSER_SUCCESS",
  GET_LISTUSER_ERROR: "GET_LISTUSER_BEGIN",
};
export const eventAction = {
  GET_EVENT_BEGIN: "GET_EVENT_BEGIN",
  GET_EVENT_SUCCESS: "GET_EVENT_SUCCESS",
  GET_EVENT_ERROR: "GET_EVENT_BEGIN",
  GET_LISTEVENT_BEGIN: "GET_LISTEVENT_BEGIN",
  GET_LISTEVENT_SUCCESS: "GET_LISTEVENT_SUCCESS",
  GET_LISTEVENT_ERROR: "GET_LISTEVENT_BEGIN",
};
export const roomAction = {
  GET_ROOM_BEGIN: "GET_ROOM_BEGIN",
  GET_ROOM_SUCCESS: "GET_ROOM_SUCCESS",
  GET_ROOM_ERROR: "GET_ROOM_BEGIN",
  GET_LISTROOM_BEGIN: "GET_LISTROOM_BEGIN",
  GET_LISTROOM_SUCCESS: "GET_LISTROOM_SUCCESS",
  GET_LISTROOM_ERROR: "GET_LISTROOM_BEGIN",
};
export const departmentAction = {
  GET_DEPRTMENT_BEGIN: "GET_DEPRTMENT_BEGIN",
  GET_DEPRTMENT_SUCCESS: "GET_DEPRTMENT_SUCCESS",
  GET_DEPRTMENT_ERROR: "GET_DEPRTMENT_BEGIN",
  GET_LISTDEPRTMENT_BEGIN: "GET_LISTDEPRTMENT_BEGIN",
  GET_LISTDEPRTMENT_SUCCESS: "G_ETLISTDEPRTMENT_SUCCESS",
  GET_LISTDEPRTMENT_ERROR: "GET_LISTDEPRTMENT_BEGIN",
};
