export const authAction = {
  LOGIN_BEGIN: "LOGIN_BEGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_BEGIN",
  LOGOUT_BEGIN: "LOGOUT_BEGIN",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",
};
export const eventAction = {
  GET_EVENT_BEGIN: "GET_EVENT_BEGIN",
  GET_EVENT_SUCCESS: "GET_EVENT_SUCCESS",
  GET_EVENT_ERROR: "GET_EVENT_BEGIN",
  GET_LISTEVENT_BEGIN: "GET_LISTEVENT_BEGIN",
  GET_LISTEVENT_SUCCESS: "GET_LISTEVENT_SUCCESS",
  GET_LISTEVENT_ERROR: "GET_LISTEVENT_BEGIN",
};
export const userAction = {
  GET_USER_BEGIN: "GET_USER_BEGIN",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_BEGIN",
  GET_LISTUSER_BEGIN: "GET_LISTUSER_BEGIN",
  GET_LISTUSER_SUCCESS: "GET_LISTUSER_SUCCESS",
  GET_LISTUSER_ERROR: "GET_LISTUSER_BEGIN",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  REFRESH: "REFRESH",
};

export const roomAction = {
  GET_ROOM_BEGIN: "GET_ROOM_BEGIN",
  GET_ROOM_SUCCESS: "GET_ROOM_SUCCESS",
  GET_ROOM_ERROR: "GET_ROOM_BEGIN",
  GET_LISTROOM_BEGIN: "GET_LISTROOM_BEGIN",
  GET_LISTROOM_SUCCESS: "GET_LISTROOM_SUCCESS",
  GET_LISTROOM_ERROR: "GET_LISTROOM_BEGIN",
  ADD_ROOM: "ADD_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  UPDATE_ROOM: "UPDATE_ROOM",
  REFRESH: "REFRESH",
};
export const departmentAction = {
  GET_DEPARTMENT_BEGIN: "GET_DEPARTMENT_BEGIN",
  GET_DEPARTMENT_SUCCESS: "GET_DEPARTMENT_SUCCESS",
  GET_DEPARTMENT_ERROR: "GET_DEPARTMENT_BEGIN",
  GET_LISTDEPARTMENT_BEGIN: "GET_LISTDEPARTMENT_BEGIN",
  GET_LISTDEPARTMENT_SUCCESS: "G_ETLISTDEPARTMENT_SUCCESS",
  GET_LISTDEPARTMENT_ERROR: "GET_LISTDEPARTMENT_BEGIN",
  ADD_DEPARTMENT: "ADD_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  REFRESH: "REFRESH",
};
